In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\sudip\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\sudip\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sudip\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\sudip\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\sudip\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [46]:
import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score,root_mean_squared_error

In [3]:
df = pd.read_csv("car-details.csv")
df.sample(5)

,name,company,model,edition,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
3952,Maruti Swift AMT VXI,Maruti,Swift,AMT VXI,2019,First,Petrol,Individual,Automatic,7500,49.84,1197.0,81.8,113.0,5.0,600000
4443,Mahindra Bolero 2011-2019 SLX,Mahindra,Bolero,2011-2019 SLX,2013,First,Diesel,Individual,Manual,60000,37.50,2523.0,62.1,195.0,7.0,550000
582,Maruti Swift Dzire LDI,Maruti,Swift,Dzire LDI,2015,First,Diesel,Individual,Manual,170000,62.50,1248.0,74.0,190.0,5.0,370000
2964,Mahindra XUV500 W4,Mahindra,XUV500,W4,2014,First,Diesel,Individual,Manual,120000,35.50,2179.0,140.0,330.0,7.0,880000
2331,Maruti Ritz VXi (ABS) BS IV,Maruti,Ritz,VXi (ABS) BS IV,2011,First,Petrol,Individual,Manual,47000,43.47,1197.0,85.8,114.0,5.0,190000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6926 entries, 0 to 6925
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6926 non-null   str
 1   company        6926 non-null   str
 2   model          6926 non-null   str
 3   edition        6926 non-null   str
 4   year           6926 non-null   int64
 5   owner          6926 non-null   str
 6   fuel           6926 non-null   str
 7   seller_type    6926 non-null   str
 8   transmission   6926 non-null   str
 9   km_driven      6926 non-null   int64
 10  mileage_mpg    6718 non-null   float64
 11  engine_cc      6718 non-null   float64
 12  max_power_bhp  6717 non-null   float64
 13  torque_nm      6717 non-null   float64
 14  seats          6718 non-null   float64
 15  selling_price  6926 non-null   int64
dtypes: float64(5), int64(3), str(8)
memory usage: 865.9 KB

In [5]:
df.isna().sum()

name               0
company            0
model              0
edition            0
year               0
owner              0
fuel               0
seller_type        0
transmission       0
km_driven          0
mileage_mpg      208
engine_cc        208
max_power_bhp    209
torque_nm        209
seats            208
selling_price      0
dtype: int64

In [6]:
df.shape

(6926, 16)

In [7]:
#only  categorical columns
df.select_dtypes(include='O').columns

C:\Users\sudip\AppData\Local\Temp\ipykernel_1124\2836548629.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='O').columns

Index(['name', 'company', 'model', 'edition', 'owner', 'fuel', 'seller_type',
       'transmission'],
      dtype='str')

In [8]:
## here use nunique to find the cardinality of the categorical columns
for col in df.select_dtypes(include='O').columns:
    print(f'column: {col}')
    print(f'cardinality: {df[col].nunique()}')
    print(df[col].unique())
    print(df[col].value_counts(normalize=True))
    print()

column: name
cardinality: 2058
<StringArray>
[                      'Maruti Swift Dzire VDI',
                 'Skoda Rapid 1.5 TDI Ambition',
                     'Honda City 2017-2020 EXi',
                    'Hyundai i20 Sportz Diesel',
                       'Maruti Swift VXI BSIII',
                'Hyundai Xcent 1.2 VTVT E Plus',
                 'Maruti Wagon R LXI DUO BSIII',
                           'Maruti 800 DX BSII',
                             'Toyota Etios VXD',
         'Ford Figo Diesel Celebration Edition',
 ...
                    'Toyota Innova 2.5 E 7 STR',
                            'Honda City ZXi AT',
                 'Ford Fiesta 1.4 Duratorq EXI',
                           'Chevrolet Cruze LT',
                  'Maruti Celerio ZXI AMT BSIV',
                        'Tata Bolt Revotron XM',
           'Tata Manza Aura (ABS) Safire BS IV',
                   'Tata Nexon 1.5 Revotorq XT',
     'Ford Freestyle Titanium Plus Diesel BSIV',
 'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV']
Length: 2058, dtype: str
name
Maruti Swift Dzire VDI                          0.017037
Maruti Alto 800 LXI                             0.010973
Maruti Alto LXi                                 0.009962
Maruti Swift VDI                                0.008663
Maruti Swift VDI BSIV                           0.008085
                                                  ...
Maruti Celerio ZXI AMT BSIV                     0.000144
Tata Bolt Revotron XM                           0.000144
Tata Manza Aura (ABS) Safire BS IV              0.000144
Tata Nexon 1.5 Revotorq XT                      0.000144
Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV    0.000144
Name: proportion, Length: 2058, dtype: float64

column: company
cardinality: 32
<StringArray>
[       'Maruti',         'Skoda',         'Honda',       'Hyundai',
        'Toyota',          'Ford',       'Renault',      'Mahindra',
          'Tata',     'Chevrolet',          'Fiat',        'Datsun',
          'Jeep', 'Mercedes-Benz',    'Mitsubishi',          'Audi',
    'Volkswagen',           'BMW',        'Nissan',         'Lexus',
        'Jaguar',          'Land',            'MG',         'Volvo',
        'Daewoo',           'Kia',         'Force',    'Ambassador',
         'Ashok',         'Isuzu',          'Opel',       'Peugeot']
Length: 32, dtype: str
company
Maruti           0.312590
Hyundai          0.182934
Mahindra         0.104389
Tata             0.093416
Honda            0.052267
Ford             0.052122
Toyota           0.051545
Chevrolet        0.031187
Renault          0.029743
Volkswagen       0.025123
Nissan           0.010540
Skoda            0.010107
Datsun           0.008230
BMW              0.006786
Mercedes-Benz    0.006642
Fiat             0.006353
Audi             0.004765
Jeep             0.003176
Mitsubishi       0.001588
Volvo            0.001299
Jaguar           0.001155
Force            0.000578
Ambassador       0.000578
Isuzu            0.000578
Land             0.000433
MG               0.000433
Daewoo           0.000433
Kia              0.000433
Lexus            0.000144
Ashok            0.000144
Opel             0.000144
Peugeot          0.000144
Name: proportion, dtype: float64

column: model
cardinality: 207
<StringArray>
[      'Swift',       'Rapid',        'City',         'i20',       'Xcent',
       'Wagon',         '800',       'Etios',        'Figo',      'Duster',
 ...
          'X3',        'Land',          'X5',         '309', 'Trailblazer',
          'MU',         'GLC',        'XC60',         'S90',    'S-Presso']
Length: 207, dtype: str
model
Swift       0.096737
Alto        0.057031
i20         0.043748
Wagon       0.035374
Innova      0.027144
              ...
MU          0.000144
GLC         0.000144
XC60        0.000144
S90         0.000144
S-Presso    0.000144
Name: proportion, Length: 207, dtype: float64

column: edition
cardinality: 1916
<StringArray>
[                     'Dzire VDI',               '1.5 TDI Ambition',
                  '2017-2020 EXi',                  'Sportz Diesel',
                      'VXI BSIII',                '1.2 VTVT E Plus',
                'R LXI DUO BSIII',                        'DX BSII',
                            'VXD',     'Diesel Celebration Edition',
 ...
                '40 TFSI Premium',                    '2.5 E 7 STR',
                         'ZXi AT',               '1.4 Duratorq EXI',
                   'ZXI AMT BSIV',                    'Revotron XM',
        'Aura (ABS) Safire BS IV',                '1.5 Revotorq XT',
      'Titanium Plus Diesel BSIV', '2.5 GX (Diesel) 8 Seater BS IV']
Length: 1916, dtype: str
edition
Dzire VDI                         0.017037
VDI                               0.015305
800 LXI                           0.010973
LXi                               0.010540
LX                                0.010396
                                    ...
ZXI AMT BSIV                      0.000144
Revotron XM                       0.000144
Aura (ABS) Safire BS IV           0.000144
1.5 Revotorq XT                   0.000144
2.5 GX (Diesel) 8 Seater BS IV    0.000144
Name: proportion, Length: 1916, dtype: float64

column: owner
cardinality: 5
<StringArray>
['First', 'Second', 'Third', 'Fourth & Above', 'Test Drive Car']
Length: 5, dtype: str
owner
First             0.612475
Second            0.285013
Third             0.077390
Fourth & Above    0.024401
Test Drive Car    0.000722
Name: proportion, dtype: float64

column: fuel
cardinality: 4
<StringArray>
['Diesel', 'Petrol', 'LPG', 'CNG']
Length: 4, dtype: str
fuel
Diesel    0.542160
Petrol    0.444268
CNG       0.008085
LPG       0.005487
Name: proportion, dtype: float64

column: seller_type
cardinality: 3
<StringArray>
['Individual', 'Dealer', 'Trustmark Dealer']
Length: 3, dtype: str
seller_type
Individual          0.897776
Dealer              0.098325
Trustmark Dealer    0.003898
Name: proportion, dtype: float64

column: transmission
cardinality: 2
<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str
transmission
Manual       0.91568
Automatic    0.08432
Name: proportion, dtype: float64

C:\Users\sudip\AppData\Local\Temp\ipykernel_1124\960836193.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='O').columns:

In [9]:
df= df.drop(columns=['name','model','edition'])
df.head()

,company,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
0,Maruti,2014,First,Diesel,Individual,Manual,145500,55.00,1248.0,74.00,190.000000,5.0,450000
1,Skoda,2014,Second,Diesel,Individual,Manual,120000,49.70,1498.0,103.52,250.000000,5.0,370000
2,Honda,2006,Third,Petrol,Individual,Manual,140000,41.60,1497.0,78.00,124.544455,5.0,158000
3,Hyundai,2010,First,Diesel,Individual,Manual,127000,54.06,1396.0,90.00,219.668960,5.0,225000
4,Maruti,2007,First,Petrol,Individual,Manual,120000,37.84,1298.0,88.20,112.776475,5.0,130000

In [10]:
df.duplicated().sum()

np.int64(19)

In [11]:
df=df.drop_duplicates()

In [12]:
df.duplicated().sum()

np.int64(0)

In [17]:
x = df.drop(columns = 'selling_price')
y = df.selling_price.copy()

print(x.shape, y.shape)

(6907, 12) (6907,)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(5525, 12) (5525,)
(1382, 12) (1382,)

In [28]:
num_cols=x_train.select_dtypes(include='number').columns.tolist()
cat_cols = [col for col in x_train.columns if col not in num_cols]
print(num_cols)
print(cat_cols)

['year', 'km_driven', 'mileage_mpg', 'engine_cc', 'max_power_bhp', 'torque_nm', 'seats']
['company', 'owner', 'fuel', 'seller_type', 'transmission']

In [ ]:
num_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('encoder', OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', num_pipe, num_cols),
    ('cat', cat_pipe, cat_cols)
])
regressor = RandomForestRegressor(
    n_estimators=10,max_depth=5 ,random_state=42)

re_model = Pipeline(steps=[
    ('pre', preprocessor),
    ('reg', regressor)
])

re_model.fit(x_train, y_train)

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['year', 'km_driven',
                                                   'mileage_mpg', 'engine_cc',
                                                   'max_power_bhp', 'torque_nm',
                                                   'seats']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['company', 'owner', 'fuel',
                                                   'seller_type',
                                                   'transmission'])])),
                ('reg',
                 RandomForestRegressor(max_depth=5, n_estimators=10,
                                       random_state=42))])

In [45]:
y_train_pred = re_model.predict(x_train)
train_rmse = root_mean_squared_error(y_train, y_train_pred)
train_mae = mean_absolute_error(y_train, y_train_pred)

y_test_pred = re_model.predict(x_test)
test_rmse = root_mean_squared_error(y_test, y_test_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

print(f'Train rmse: {train_rmse}')
print()
print(f'Train mae: {train_mae}')
print()
print(f'Test rmse: {test_rmse}')
print()
print(f'Test mae: {test_mae}')

Train rmse: 169947.48964050272

Train mae: 103527.92830970083

Test rmse: 172392.1313605195

Test mae: 105525.95021843615